language: python
python:
  - "3.5"
  - "3.6"
env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VIRTUALENVS=1
before_install: sudo apt-get install git-all
# command to install dependencies
install: make setup
# # command to run tests
script: make tox-test
